# File: Data.py
import sqlite3, ast, os, math
from bs4 import BeautifulSoup
from urllib.request import urlopen
import lxml
import requests
from lxml import html
import pycurl, json

Filelist= os.listdir("C:\PythonFiles")
Quer = 'Insert into Players values ('
for i in range(0, 114):
	Quer+="?,"
Quer+= ("?)")			

roles= ("Top", "Jungle", "Middle", "ADC", "Support")
db = sqlite3.connect('lolDB.db')
cursor = db.cursor()
cursor.execute('''DROP TABLE Teams''')
cursor.execute('''DROP TABLE Players''')


cursor.execute('''CREATE TABLE Teams(name string, gameid integer, duration integer, season integer, side string,
                  win string, firstBlood string, firstTower string, firstBaron string,
				  towerKills integer, inhibitorKills integer, baronKills integer,
				  dragonKills integer, firstBan integer, secondBan integer, thirdBan integer, opponent string)
               ''')
cursor.execute('''CREATE TABLE Players(gameid integer, name string, teamId string, role string, opponent string,  
                  champion integer, Patch integer, side string, firstBlood string, firstTower string, win integer, duration integer,
				  towerKills integer, inhibitorKills integer, kills integer, deaths integer, assists integer, largestKillingSpree integer,
				  largestMultiKill integer, killingSprees integer, longestTimeSpentLiving integer,
				  doubleKills integer, tripleKills integer, quadraKills integer, pentaKills integer,
				  unrealKills integer, totalDamageDealt integer, magicDamageDealt integer, physicalDamageDealt integer,
				  trueDamageDealt integer, largestCriticalStrike integer, totalDamageDealtToChampions integer,
				  magicDamageDealtToChampions integer, physicalDamageDealtToChampions integer, trueDamageDealtToChampions integer,
				  totalHeal integer, totalUnitsHealed integer, totalDamageTaken integer, magicalDamageTaken integer,
				  physicalDamageTaken integer, trueDamageTaken integer, goldEarned integer, goldSpent integer, turretKills integer,
				  totalMinionsKilled integer, neutralMinionsKilled integer, neutralMinionsKilledTeamJungle integer,
				  neutralMinionsKilledEnemyJungle integer, totalTimeCrowdControlDealt integer, champLevel integer, 
				  visionWardsBoughtInGame integer, sightWardsBoughtInGame integer, wardsPlaced integer, wardsKilled integer, 
				  firstBloodKill integer, firstBloodAssist integer, firstTowerKill integer, firstTowerAssist integer, 
				  firstInhibitorKill integer, firstInhibitorAssist integer, creepsPerMinDelta1020 integer, creepsPerMinDelta2030 integer,
				  creepsPerMinDelta010 integer,creepsPerMinDeltas30end integer, xpPerMinDelta1020 integer, 
				  xpPerMinDelta2030 integer, xpPerMinDelta010 integer, xpPerMinDeltas30end integer, goldPerMinDeltas1020 integer, 
				  goldPerMinDeltas2030 integer, goldPerMinDeltas010 integer, goldPerMinDeltas30end integer, 
				  damageTakenPerMinDeltas1020 integer, damageTakenPerMinDeltas2030 integer, damageTakenPerMinDeltas010,
				  damageTakenPerMinDeltas30end integer,
				  totalDamageDealtDif integer, magicDamageDealtDif integer, physicalDamageDealtDif integer,
				  totalDamageDealtToChampionsDif integer, magicDamageDealtToChampionsDif integer, physicalDamageDealtToChampionsDif integer,
				  totalHealDif integer, totalUnitsHealedDif integer, totalDamageTakenDif integer, magicalDamageTakenDif integer,
				  physicalDamageTakenDif integer, goldEarnedDif integer, goldSpentDif integer,
				  totalMinionsKilledDif integer, neutralMinionsKilledDif integer, neutralMinionsKilledTeamJungleDif integer,
				  neutralMinionsKilledEnemyJungleDif integer, totalTimeCrowdControlDealtDif integer, champLevelDif integer, 
				  visionWardsBoughtInGameDif integer, sightWardsBoughtInGameDif integer, wardsPlacedDif integer, wardsKilledDif integer, 
				  creepsPerMinDelta1020Dif integer, creepsPerMinDelta2030Dif integer, creepsPerMinDelta010Dif integer,
				  creepsPerMinDeltas30endDif integer, xpPerMinDelta1020Dif integer, xpPerMinDelta2030Dif integer,
				  xpPerMinDelta010Dif integer, xpPerMinDeltas30endDif integer, goldPerMinDeltas1020Dif integer, 
				  goldPerMinDeltas2030Dif integer, goldPerMinDeltas010Dif integer, goldPerMinDeltas30endDif integer, 
				  damageTakenPerMinDeltas1020Dif integer, damageTakenPerMinDeltas2030Dif integer, damageTakenPerMinDeltas010Dif integer,
				  damageTakenPerMinDeltas30endDif integer)
				  ''')	



for item in Filelist:
	if ".json" in item:
		curr_dict= json.load(open(item))
		
		for tem in curr_dict['teams']:
			if tem['teamId']== 100:
				q= "Insert into Teams values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
				cursor.execute(q, 
					(curr_dict['participantIdentities'][0]['player']['summonerName'][0:3], curr_dict['gameId'], curr_dict['gameDuration']/60, 
					curr_dict['gameVersion'], "blue", tem['win'], tem['firstBlood'], tem["firstTower"], tem["firstBaron"],
					tem['towerKills'], tem['inhibitorKills'], tem['baronKills'], tem['dragonKills'], tem['bans'][-1]['championId'],
					tem['bans'][0]['championId'], tem['bans'][1]['championId'], 
					curr_dict['participantIdentities'][7]['player']['summonerName'][0:3])
					)
			else:
				cursor.execute("insert into Teams values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", 
					(curr_dict['participantIdentities'][7]['player']['summonerName'][0:3], curr_dict['gameId'], curr_dict['gameDuration']/60, 
					curr_dict['gameVersion'], "red", tem['win'], tem['firstBlood'], tem["firstTower"], tem["firstBaron"],
					tem['towerKills'], tem['inhibitorKills'], tem['baronKills'], tem['dragonKills'], tem['bans'][-1]['championId'],
					tem['bans'][0]['championId'], tem['bans'][1]['championId'], 
					curr_dict['participantIdentities'][1]['player']['summonerName'][0:3])
					)
		for i, participant in zip(range(0, 10), curr_dict['participants']):
			if curr_dict['gameDuration']>3000:
				if i<5:
					cursor.execute(Quer,
						(curr_dict['gameId'], curr_dict['participantIdentities'][i]['player']['summonerName'][3:].lower().replace(" ", ""), 
						curr_dict['participantIdentities'][0]['player']['summonerName'][0:3], roles[i], curr_dict['participantIdentities'][i+5]['player']['summonerName'][3:].lower().replace(" ", ""),
						participant['championId'], curr_dict['gameVersion'], "blue", participant['stats']['firstBloodKill'], participant['stats']['firstTowerKill'], participant['stats']['win'], curr_dict['gameDuration']/60,
						participant['stats']['turretKills'], participant['stats']['inhibitorKills'], participant['stats']['kills'],
						participant['stats']['deaths'], participant['stats']['assists'], participant['stats']['largestKillingSpree'], 
						participant['stats']['largestMultiKill'], participant['stats']['killingSprees'], participant['stats']['longestTimeSpentLiving'], 
						participant['stats']['doubleKills'], participant['stats']['tripleKills'], participant['stats']['quadraKills'], 
						participant['stats']['pentaKills'],  participant['stats']['unrealKills'], participant['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt'], participant['stats']['physicalDamageDealt'], participant['stats']['trueDamageDealt'], 
						participant['stats']['largestCriticalStrike'], participant['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions'], participant['stats']['physicalDamageDealtToChampions'], 
						participant['stats']['trueDamageDealtToChampions'], participant['stats']['totalHeal'], participant['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken'], participant['stats']['magicalDamageTaken'], participant['stats']['physicalDamageTaken'], 
						participant['stats']['trueDamageTaken'], participant['stats']['goldEarned'], participant['stats']['goldSpent'], 
						participant['stats']['turretKills'], participant['stats']['totalMinionsKilled'], participant['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle'], participant['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt'], participant['stats']['champLevel'], participant['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced'], participant['stats']['wardsKilled'], participant['stats']['firstBloodKill'], 
						participant['stats']['firstBloodAssist'], participant['stats']['firstTowerKill'], participant['stats']['firstTowerAssist'], 
						participant['stats']['firstInhibitorKill'], participant['stats']['firstInhibitorAssist'], 
						participant['timeline']['creepsPerMinDeltas']['10-20'], participant['timeline']['creepsPerMinDeltas']['20-30'], 
						participant['timeline']['creepsPerMinDeltas']['0-10'], participant['timeline']['creepsPerMinDeltas']['30-end'], 
						participant['timeline']['xpPerMinDeltas']['10-20'], participant['timeline']['xpPerMinDeltas']['20-30'], 
						participant['timeline']['xpPerMinDeltas']['0-10'], participant['timeline']['xpPerMinDeltas']['30-end'], 
						participant['timeline']['goldPerMinDeltas']['10-20'], participant['timeline']['goldPerMinDeltas']['20-30'], 
						participant['timeline']['goldPerMinDeltas']['0-10'], participant['timeline']['goldPerMinDeltas']['30-end'], 
						participant['timeline']['damageTakenPerMinDeltas']['10-20'], participant['timeline']['damageTakenPerMinDeltas']['20-30'], 
						participant['timeline']['damageTakenPerMinDeltas']['0-10'], participant['timeline']['damageTakenPerMinDeltas']['30-end'],  
						participant['stats']['totalDamageDealt']-curr_dict['participants'][i+5]['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt']-curr_dict['participants'][i+5]['stats']['magicDamageDealt'], 
						participant['stats']['physicalDamageDealt']-curr_dict['participants'][i+5]['stats']['physicalDamageDealt'],
						participant['stats']['totalDamageDealtToChampions']-curr_dict['participants'][i+5]['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions']-curr_dict['participants'][i+5]['stats']['magicDamageDealtToChampions'],
						participant['stats']['physicalDamageDealtToChampions']-curr_dict['participants'][i+5]['stats']['physicalDamageDealtToChampions'],
						participant['stats']['totalHeal']-curr_dict['participants'][i+5]['stats']['totalHeal'], 
						participant['stats']['totalUnitsHealed']-curr_dict['participants'][i+5]['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken']-curr_dict['participants'][i+5]['stats']['totalDamageTaken'], 
						participant['stats']['magicalDamageTaken']-curr_dict['participants'][i+5]['stats']['magicalDamageTaken'],
						participant['stats']['physicalDamageTaken']-curr_dict['participants'][i+5]['stats']['physicalDamageTaken'], 
						participant['stats']['goldEarned']-curr_dict['participants'][i+5]['stats']['goldEarned'], 
						participant['stats']['goldSpent']-curr_dict['participants'][i+5]['stats']['goldSpent'], 
						participant['stats']['totalMinionsKilled']-curr_dict['participants'][i+5]['stats']['totalMinionsKilled'], 
						participant['stats']['neutralMinionsKilled']-curr_dict['participants'][i+5]['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle']-curr_dict['participants'][i+5]['stats']['neutralMinionsKilledTeamJungle'], 
						participant['stats']['neutralMinionsKilledEnemyJungle']-curr_dict['participants'][i+5]['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt']-curr_dict['participants'][i+5]['stats']['totalTimeCrowdControlDealt'],
						participant['stats']['champLevel']-curr_dict['participants'][i+5]['stats']['champLevel'], 
						participant['stats']['visionWardsBoughtInGame']-curr_dict['participants'][i+5]['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame']-curr_dict['participants'][i+5]['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced']-curr_dict['participants'][i+5]['stats']['wardsPlaced'], 
						participant['stats']['wardsKilled']-curr_dict['participants'][i+5]['stats']['wardsKilled'], 
						participant['timeline']['creepsPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['creepsPerMinDeltas']['10-20'], 
						participant['timeline']['creepsPerMinDeltas']['20-30']-curr_dict['participants'][i+5]['timeline']['creepsPerMinDeltas']['20-30'], 
						participant['timeline']['creepsPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['creepsPerMinDeltas']['0-10'], 
						participant['timeline']['creepsPerMinDeltas']['30-end']-curr_dict['participants'][i+5]['timeline']['creepsPerMinDeltas']['30-end'], 
						participant['timeline']['xpPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['xpPerMinDeltas']['10-20'], 
						participant['timeline']['xpPerMinDeltas']['20-30']-curr_dict['participants'][i+5]['timeline']['xpPerMinDeltas']['20-30'], 
						participant['timeline']['xpPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['xpPerMinDeltas']['0-10'], 
						participant['timeline']['xpPerMinDeltas']['30-end']-curr_dict['participants'][i+5]['timeline']['xpPerMinDeltas']['30-end'], 
						participant['timeline']['goldPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['goldPerMinDeltas']['10-20'], 
						participant['timeline']['goldPerMinDeltas']['20-30']-curr_dict['participants'][i+5]['timeline']['goldPerMinDeltas']['20-30'], 
						participant['timeline']['goldPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['goldPerMinDeltas']['0-10'],
						participant['timeline']['goldPerMinDeltas']['30-end']-curr_dict['participants'][i+5]['timeline']['goldPerMinDeltas']['30-end'], 
						participant['timeline']['damageTakenPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['damageTakenPerMinDeltas']['10-20'], 
						participant['timeline']['damageTakenPerMinDeltas']['20-30']-curr_dict['participants'][i+5]['timeline']['damageTakenPerMinDeltas']['20-30'], 
						participant['timeline']['damageTakenPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['damageTakenPerMinDeltas']['0-10'],
						participant['timeline']['damageTakenPerMinDeltas']['30-end']-curr_dict['participants'][i+5]['timeline']['damageTakenPerMinDeltas']['30-end'])
					)
				else:
					cursor.execute(Quer,
						(curr_dict['gameId'], curr_dict['participantIdentities'][i]['player']['summonerName'][3:].lower().replace(" ", ""), 
						curr_dict['participantIdentities'][7]['player']['summonerName'][0:3],roles[i-5], 
						curr_dict['participantIdentities'][i-5]['player']['summonerName'][3:].lower().replace(" ", ""),
						participant['championId'], curr_dict['gameVersion'], "red", participant['stats']['firstBloodKill'], participant['stats']['firstTowerKill'], participant['stats']['win'], curr_dict['gameDuration']/60,
						participant['stats']['turretKills'], participant['stats']['inhibitorKills'], participant['stats']['kills'],
						participant['stats']['deaths'], participant['stats']['assists'], participant['stats']['largestKillingSpree'], 
						participant['stats']['largestMultiKill'], participant['stats']['killingSprees'], participant['stats']['longestTimeSpentLiving'], 
						participant['stats']['doubleKills'], participant['stats']['tripleKills'], participant['stats']['quadraKills'], 
						participant['stats']['pentaKills'],  participant['stats']['unrealKills'], participant['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt'], participant['stats']['physicalDamageDealt'], participant['stats']['trueDamageDealt'], 
						participant['stats']['largestCriticalStrike'], participant['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions'], participant['stats']['physicalDamageDealtToChampions'], 
						participant['stats']['trueDamageDealtToChampions'], participant['stats']['totalHeal'], participant['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken'], participant['stats']['magicalDamageTaken'], participant['stats']['physicalDamageTaken'], 
						participant['stats']['trueDamageTaken'], participant['stats']['goldEarned'], participant['stats']['goldSpent'], 
						participant['stats']['turretKills'], participant['stats']['totalMinionsKilled'], participant['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle'], participant['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt'], participant['stats']['champLevel'], participant['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced'], participant['stats']['wardsKilled'], participant['stats']['firstBloodKill'], 
						participant['stats']['firstBloodAssist'], participant['stats']['firstTowerKill'], participant['stats']['firstTowerAssist'], 
						participant['stats']['firstInhibitorKill'], participant['stats']['firstInhibitorAssist'], 
						participant['timeline']['creepsPerMinDeltas']['10-20'], participant['timeline']['creepsPerMinDeltas']['20-30'], 
						participant['timeline']['creepsPerMinDeltas']['0-10'], participant['timeline']['creepsPerMinDeltas']['30-end'], 
						participant['timeline']['xpPerMinDeltas']['10-20'], participant['timeline']['xpPerMinDeltas']['20-30'], 
						participant['timeline']['xpPerMinDeltas']['0-10'], participant['timeline']['xpPerMinDeltas']['30-end'], 
						participant['timeline']['goldPerMinDeltas']['10-20'], participant['timeline']['goldPerMinDeltas']['20-30'], 
						participant['timeline']['goldPerMinDeltas']['0-10'], participant['timeline']['goldPerMinDeltas']['30-end'], 
						participant['timeline']['damageTakenPerMinDeltas']['10-20'], participant['timeline']['damageTakenPerMinDeltas']['20-30'], 
						participant['timeline']['damageTakenPerMinDeltas']['0-10'], participant['timeline']['damageTakenPerMinDeltas']['30-end'], 

						participant['stats']['totalDamageDealt']-curr_dict['participants'][i-5]['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt']-curr_dict['participants'][i-5]['stats']['magicDamageDealt'], 
						participant['stats']['physicalDamageDealt']-curr_dict['participants'][i-5]['stats']['physicalDamageDealt'],
						participant['stats']['totalDamageDealtToChampions']-curr_dict['participants'][i-5]['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions']-curr_dict['participants'][i-5]['stats']['magicDamageDealtToChampions'],
						participant['stats']['physicalDamageDealtToChampions']-curr_dict['participants'][i-5]['stats']['physicalDamageDealtToChampions'],
						participant['stats']['totalHeal']-curr_dict['participants'][i-5]['stats']['totalHeal'], 
						participant['stats']['totalUnitsHealed']-curr_dict['participants'][i-5]['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken']-curr_dict['participants'][i-5]['stats']['totalDamageTaken'], 
						participant['stats']['magicalDamageTaken']-curr_dict['participants'][i-5]['stats']['magicalDamageTaken'],
						participant['stats']['physicalDamageTaken']-curr_dict['participants'][i-5]['stats']['physicalDamageTaken'], 
						participant['stats']['goldEarned']-curr_dict['participants'][i-5]['stats']['goldEarned'], 
						participant['stats']['goldSpent']-curr_dict['participants'][i-5]['stats']['goldSpent'], 
						participant['stats']['totalMinionsKilled']-curr_dict['participants'][i-5]['stats']['totalMinionsKilled'], 
						participant['stats']['neutralMinionsKilled']-curr_dict['participants'][i-5]['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle']-curr_dict['participants'][i-5]['stats']['neutralMinionsKilledTeamJungle'], 
						participant['stats']['neutralMinionsKilledEnemyJungle']-curr_dict['participants'][i-5]['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt']-curr_dict['participants'][i-5]['stats']['totalTimeCrowdControlDealt'],
						participant['stats']['champLevel']-curr_dict['participants'][i-5]['stats']['champLevel'], 
						participant['stats']['visionWardsBoughtInGame']-curr_dict['participants'][i-5]['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame']-curr_dict['participants'][i-5]['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced']-curr_dict['participants'][i-5]['stats']['wardsPlaced'], 
						participant['stats']['wardsKilled']-curr_dict['participants'][i-5]['stats']['wardsKilled'], 
						participant['timeline']['creepsPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['creepsPerMinDeltas']['10-20'], 
						participant['timeline']['creepsPerMinDeltas']['20-30']-curr_dict['participants'][i-5]['timeline']['creepsPerMinDeltas']['20-30'], 
						participant['timeline']['creepsPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['creepsPerMinDeltas']['0-10'], 
						participant['timeline']['creepsPerMinDeltas']['30-end']-curr_dict['participants'][i-5]['timeline']['creepsPerMinDeltas']['30-end'], 
						participant['timeline']['xpPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['xpPerMinDeltas']['10-20'], 
						participant['timeline']['xpPerMinDeltas']['20-30']-curr_dict['participants'][i-5]['timeline']['xpPerMinDeltas']['20-30'], 
						participant['timeline']['xpPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['xpPerMinDeltas']['0-10'], 
						participant['timeline']['xpPerMinDeltas']['30-end']-curr_dict['participants'][i-5]['timeline']['xpPerMinDeltas']['30-end'], 
						participant['timeline']['goldPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['goldPerMinDeltas']['10-20'], 
						participant['timeline']['goldPerMinDeltas']['20-30']-curr_dict['participants'][i-5]['timeline']['goldPerMinDeltas']['20-30'], 
						participant['timeline']['goldPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['goldPerMinDeltas']['0-10'],
						participant['timeline']['goldPerMinDeltas']['30-end']-curr_dict['participants'][i-5]['timeline']['goldPerMinDeltas']['30-end'], 
						participant['timeline']['damageTakenPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['damageTakenPerMinDeltas']['10-20'], 
						participant['timeline']['damageTakenPerMinDeltas']['20-30']-curr_dict['participants'][i-5]['timeline']['damageTakenPerMinDeltas']['20-30'], 
						participant['timeline']['damageTakenPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['damageTakenPerMinDeltas']['0-10'],
						participant['timeline']['damageTakenPerMinDeltas']['30-end']-curr_dict['participants'][i-5]['timeline']['damageTakenPerMinDeltas']['30-end'])
					)
			elif curr_dict['gameDuration']>1800:
				if i<5:
					cursor.execute(Quer,
						(curr_dict['gameId'], curr_dict['participantIdentities'][i]['player']['summonerName'][3:].lower().replace(" ", ""), 
						curr_dict['participantIdentities'][0]['player']['summonerName'][0:3],roles[i], 
						curr_dict['participantIdentities'][i+5]['player']['summonerName'][3:].lower().replace(" ", ""), 
						participant['championId'], curr_dict['gameVersion'], "red", participant['stats']['firstBloodKill'], participant['stats']['firstTowerKill'], participant['stats']['win'],curr_dict['gameDuration']/60,
						participant['stats']['turretKills'], participant['stats']['inhibitorKills'], participant['stats']['kills'],
						participant['stats']['deaths'], participant['stats']['assists'], participant['stats']['largestKillingSpree'], 
						participant['stats']['largestMultiKill'], participant['stats']['killingSprees'], participant['stats']['longestTimeSpentLiving'], 
						participant['stats']['doubleKills'], participant['stats']['tripleKills'], participant['stats']['quadraKills'], 
						participant['stats']['pentaKills'],  participant['stats']['unrealKills'], participant['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt'], participant['stats']['physicalDamageDealt'], participant['stats']['trueDamageDealt'], 
						participant['stats']['largestCriticalStrike'], participant['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions'], participant['stats']['physicalDamageDealtToChampions'], 
						participant['stats']['trueDamageDealtToChampions'], participant['stats']['totalHeal'], participant['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken'], participant['stats']['magicalDamageTaken'], participant['stats']['physicalDamageTaken'], 
						participant['stats']['trueDamageTaken'], participant['stats']['goldEarned'], participant['stats']['goldSpent'], 
						participant['stats']['turretKills'], participant['stats']['totalMinionsKilled'], participant['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle'], participant['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt'], participant['stats']['champLevel'], participant['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced'], participant['stats']['wardsKilled'], participant['stats']['firstBloodKill'], 
						participant['stats']['firstBloodAssist'], participant['stats']['firstTowerKill'], participant['stats']['firstTowerAssist'], 
						participant['stats']['firstInhibitorKill'], participant['stats']['firstInhibitorAssist'], 
						participant['timeline']['creepsPerMinDeltas']['10-20'], participant['timeline']['creepsPerMinDeltas']['20-30'], 
						participant['timeline']['creepsPerMinDeltas']['0-10'], None, 
						participant['timeline']['xpPerMinDeltas']['10-20'], participant['timeline']['xpPerMinDeltas']['20-30'], 
						participant['timeline']['xpPerMinDeltas']['0-10'], None, 
						participant['timeline']['goldPerMinDeltas']['10-20'], participant['timeline']['goldPerMinDeltas']['20-30'], 
						participant['timeline']['goldPerMinDeltas']['0-10'], None, 
						participant['timeline']['damageTakenPerMinDeltas']['10-20'], participant['timeline']['damageTakenPerMinDeltas']['20-30'], 
						participant['timeline']['damageTakenPerMinDeltas']['0-10'], None, 
						participant['stats']['totalDamageDealt']-curr_dict['participants'][i+5]['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt']-curr_dict['participants'][i+5]['stats']['magicDamageDealt'], 
						participant['stats']['physicalDamageDealt']-curr_dict['participants'][i+5]['stats']['physicalDamageDealt'],
						participant['stats']['totalDamageDealtToChampions']-curr_dict['participants'][i+5]['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions']-curr_dict['participants'][i+5]['stats']['magicDamageDealtToChampions'],
						participant['stats']['physicalDamageDealtToChampions']-curr_dict['participants'][i+5]['stats']['physicalDamageDealtToChampions'],
						participant['stats']['totalHeal']-curr_dict['participants'][i+5]['stats']['totalHeal'], 
						participant['stats']['totalUnitsHealed']-curr_dict['participants'][i+5]['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken']-curr_dict['participants'][i+5]['stats']['totalDamageTaken'], 
						participant['stats']['magicalDamageTaken']-curr_dict['participants'][i+5]['stats']['magicalDamageTaken'],
						participant['stats']['physicalDamageTaken']-curr_dict['participants'][i+5]['stats']['physicalDamageTaken'], 
						participant['stats']['goldEarned']-curr_dict['participants'][i+5]['stats']['goldEarned'], 
						participant['stats']['goldSpent']-curr_dict['participants'][i+5]['stats']['goldSpent'], 
						participant['stats']['totalMinionsKilled']-curr_dict['participants'][i+5]['stats']['totalMinionsKilled'], 
						participant['stats']['neutralMinionsKilled']-curr_dict['participants'][i+5]['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle']-curr_dict['participants'][i+5]['stats']['neutralMinionsKilledTeamJungle'], 
						participant['stats']['neutralMinionsKilledEnemyJungle']-curr_dict['participants'][i+5]['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt']-curr_dict['participants'][i+5]['stats']['totalTimeCrowdControlDealt'],
						participant['stats']['champLevel']-curr_dict['participants'][i+5]['stats']['champLevel'], 
						participant['stats']['visionWardsBoughtInGame']-curr_dict['participants'][i+5]['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame']-curr_dict['participants'][i+5]['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced']-curr_dict['participants'][i+5]['stats']['wardsPlaced'], 
						participant['stats']['wardsKilled']-curr_dict['participants'][i+5]['stats']['wardsKilled'], 
						participant['timeline']['creepsPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['creepsPerMinDeltas']['10-20'], 
						participant['timeline']['creepsPerMinDeltas']['20-30']-curr_dict['participants'][i+5]['timeline']['creepsPerMinDeltas']['20-30'], 
						participant['timeline']['creepsPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['creepsPerMinDeltas']['0-10'], 
						None, 
						participant['timeline']['xpPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['xpPerMinDeltas']['10-20'], 
						participant['timeline']['xpPerMinDeltas']['20-30']-curr_dict['participants'][i+5]['timeline']['xpPerMinDeltas']['20-30'], 
						participant['timeline']['xpPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['xpPerMinDeltas']['0-10'], 
						None, 
						participant['timeline']['goldPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['goldPerMinDeltas']['10-20'], 
						participant['timeline']['goldPerMinDeltas']['20-30']-curr_dict['participants'][i+5]['timeline']['goldPerMinDeltas']['20-30'], 
						participant['timeline']['goldPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['goldPerMinDeltas']['0-10'],
						None, 
						participant['timeline']['damageTakenPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['damageTakenPerMinDeltas']['10-20'], 
						participant['timeline']['damageTakenPerMinDeltas']['20-30']-curr_dict['participants'][i+5]['timeline']['damageTakenPerMinDeltas']['20-30'], 
						participant['timeline']['damageTakenPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['damageTakenPerMinDeltas']['0-10'],
						None)
					)
				else:	
					cursor.execute(Quer,
						(curr_dict['gameId'], curr_dict['participantIdentities'][i]['player']['summonerName'][3:].lower().replace(" ", ""), 
						curr_dict['participantIdentities'][7]['player']['summonerName'][0:3], roles[i-5],
						curr_dict['participantIdentities'][i-5]['player']['summonerName'][3:].lower().replace(" ", ""), 
						participant['championId'], curr_dict['gameVersion'], "blue", participant['stats']['firstBloodKill'], participant['stats']['firstTowerKill'],participant['stats']['win'], curr_dict['gameDuration']/60,
						participant['stats']['turretKills'], participant['stats']['inhibitorKills'], participant['stats']['kills'],
						participant['stats']['deaths'], participant['stats']['assists'], participant['stats']['largestKillingSpree'], 
						participant['stats']['largestMultiKill'], participant['stats']['killingSprees'], participant['stats']['longestTimeSpentLiving'], 
						participant['stats']['doubleKills'], participant['stats']['tripleKills'], participant['stats']['quadraKills'], 
						participant['stats']['pentaKills'],  participant['stats']['unrealKills'], participant['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt'], participant['stats']['physicalDamageDealt'], participant['stats']['trueDamageDealt'], 
						participant['stats']['largestCriticalStrike'], participant['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions'], participant['stats']['physicalDamageDealtToChampions'], 
						participant['stats']['trueDamageDealtToChampions'], participant['stats']['totalHeal'], participant['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken'], participant['stats']['magicalDamageTaken'], participant['stats']['physicalDamageTaken'], 
						participant['stats']['trueDamageTaken'], participant['stats']['goldEarned'], participant['stats']['goldSpent'], 
						participant['stats']['turretKills'], participant['stats']['totalMinionsKilled'], participant['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle'], participant['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt'], participant['stats']['champLevel'], participant['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced'], participant['stats']['wardsKilled'], participant['stats']['firstBloodKill'], 
						participant['stats']['firstBloodAssist'], participant['stats']['firstTowerKill'], participant['stats']['firstTowerAssist'], 
						participant['stats']['firstInhibitorKill'], participant['stats']['firstInhibitorAssist'], 
						participant['timeline']['creepsPerMinDeltas']['10-20'], participant['timeline']['creepsPerMinDeltas']['20-30'], 
						participant['timeline']['creepsPerMinDeltas']['0-10'], None, 
						participant['timeline']['xpPerMinDeltas']['10-20'], participant['timeline']['xpPerMinDeltas']['20-30'], 
						participant['timeline']['xpPerMinDeltas']['0-10'], None, 
						participant['timeline']['goldPerMinDeltas']['10-20'], participant['timeline']['goldPerMinDeltas']['20-30'], 
						participant['timeline']['goldPerMinDeltas']['0-10'], None, 
						participant['timeline']['damageTakenPerMinDeltas']['10-20'], participant['timeline']['damageTakenPerMinDeltas']['20-30'], 
						participant['timeline']['damageTakenPerMinDeltas']['0-10'], None, 
						participant['stats']['totalDamageDealt']-curr_dict['participants'][i-5]['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt']-curr_dict['participants'][i-5]['stats']['magicDamageDealt'], 
						participant['stats']['physicalDamageDealt']-curr_dict['participants'][i-5]['stats']['physicalDamageDealt'],
						participant['stats']['totalDamageDealtToChampions']-curr_dict['participants'][i-5]['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions']-curr_dict['participants'][i-5]['stats']['magicDamageDealtToChampions'],
						participant['stats']['physicalDamageDealtToChampions']-curr_dict['participants'][i-5]['stats']['physicalDamageDealtToChampions'],
						participant['stats']['totalHeal']-curr_dict['participants'][i-5]['stats']['totalHeal'], 
						participant['stats']['totalUnitsHealed']-curr_dict['participants'][i-5]['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken']-curr_dict['participants'][i-5]['stats']['totalDamageTaken'], 
						participant['stats']['magicalDamageTaken']-curr_dict['participants'][i-5]['stats']['magicalDamageTaken'],
						participant['stats']['physicalDamageTaken']-curr_dict['participants'][i-5]['stats']['physicalDamageTaken'], 
						participant['stats']['goldEarned']-curr_dict['participants'][i-5]['stats']['goldEarned'], 
						participant['stats']['goldSpent']-curr_dict['participants'][i-5]['stats']['goldSpent'], 
						participant['stats']['totalMinionsKilled']-curr_dict['participants'][i-5]['stats']['totalMinionsKilled'], 
						participant['stats']['neutralMinionsKilled']-curr_dict['participants'][i-5]['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle']-curr_dict['participants'][i-5]['stats']['neutralMinionsKilledTeamJungle'], 
						participant['stats']['neutralMinionsKilledEnemyJungle']-curr_dict['participants'][i-5]['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt']-curr_dict['participants'][i-5]['stats']['totalTimeCrowdControlDealt'],
						participant['stats']['champLevel']-curr_dict['participants'][i-5]['stats']['champLevel'], 
						participant['stats']['visionWardsBoughtInGame']-curr_dict['participants'][i-5]['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame']-curr_dict['participants'][i-5]['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced']-curr_dict['participants'][i-5]['stats']['wardsPlaced'], 
						participant['stats']['wardsKilled']-curr_dict['participants'][i-5]['stats']['wardsKilled'], 
						participant['timeline']['creepsPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['creepsPerMinDeltas']['10-20'], 
						participant['timeline']['creepsPerMinDeltas']['20-30']-curr_dict['participants'][i-5]['timeline']['creepsPerMinDeltas']['20-30'], 
						participant['timeline']['creepsPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['creepsPerMinDeltas']['0-10'], 
						None, 
						participant['timeline']['xpPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['xpPerMinDeltas']['10-20'], 
						participant['timeline']['xpPerMinDeltas']['20-30']-curr_dict['participants'][i-5]['timeline']['xpPerMinDeltas']['20-30'], 
						participant['timeline']['xpPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['xpPerMinDeltas']['0-10'], 
						None, 
						participant['timeline']['goldPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['goldPerMinDeltas']['10-20'], 
						participant['timeline']['goldPerMinDeltas']['20-30']-curr_dict['participants'][i-5]['timeline']['goldPerMinDeltas']['20-30'], 
						participant['timeline']['goldPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['goldPerMinDeltas']['0-10'],
						None, 
						participant['timeline']['damageTakenPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['damageTakenPerMinDeltas']['10-20'], 
						participant['timeline']['damageTakenPerMinDeltas']['20-30']-curr_dict['participants'][i-5]['timeline']['damageTakenPerMinDeltas']['20-30'], 
						participant['timeline']['damageTakenPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['damageTakenPerMinDeltas']['0-10'],
						None)
					)
			else:
				if i<5:
					cursor.execute(Quer,
						(curr_dict['gameId'], curr_dict['participantIdentities'][i]['player']['summonerName'][3:].lower().replace(" ", ""), 
						curr_dict['participantIdentities'][0]['player']['summonerName'][0:3],roles[i],
						curr_dict['participantIdentities'][i+5]['player']['summonerName'][3:].lower().replace(" ", ""),  
						participant['championId'], curr_dict['gameVersion'], "red", participant['stats']['firstBloodKill'], participant['stats']['firstTowerKill'],participant['stats']['win'], curr_dict['gameDuration']/60,
						participant['stats']['turretKills'], participant['stats']['inhibitorKills'], participant['stats']['kills'],
						participant['stats']['deaths'], participant['stats']['assists'], participant['stats']['largestKillingSpree'], 
						participant['stats']['largestMultiKill'], participant['stats']['killingSprees'], participant['stats']['longestTimeSpentLiving'], 
						participant['stats']['doubleKills'], participant['stats']['tripleKills'], participant['stats']['quadraKills'], 
						participant['stats']['pentaKills'],  participant['stats']['unrealKills'], participant['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt'], participant['stats']['physicalDamageDealt'], participant['stats']['trueDamageDealt'], 
						participant['stats']['largestCriticalStrike'], participant['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions'], participant['stats']['physicalDamageDealtToChampions'], 
						participant['stats']['trueDamageDealtToChampions'], participant['stats']['totalHeal'], participant['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken'], participant['stats']['magicalDamageTaken'], participant['stats']['physicalDamageTaken'], 
						participant['stats']['trueDamageTaken'], participant['stats']['goldEarned'], participant['stats']['goldSpent'], 
						participant['stats']['turretKills'], participant['stats']['totalMinionsKilled'], participant['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle'], participant['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt'], participant['stats']['champLevel'], participant['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced'], participant['stats']['wardsKilled'], participant['stats']['firstBloodKill'], 
						participant['stats']['firstBloodAssist'], participant['stats']['firstTowerKill'], participant['stats']['firstTowerAssist'], 
						participant['stats']['firstInhibitorKill'], participant['stats']['firstInhibitorAssist'], 
						participant['timeline']['creepsPerMinDeltas']['10-20'], None, 
						participant['timeline']['creepsPerMinDeltas']['0-10'], None, 
						participant['timeline']['xpPerMinDeltas']['10-20'], None, 
						participant['timeline']['xpPerMinDeltas']['0-10'], None, 
						participant['timeline']['goldPerMinDeltas']['10-20'], None, 
						participant['timeline']['goldPerMinDeltas']['0-10'], None, 
						participant['timeline']['damageTakenPerMinDeltas']['10-20'], None, 
						participant['timeline']['damageTakenPerMinDeltas']['0-10'], None, 
						participant['stats']['totalDamageDealt']-curr_dict['participants'][i+5]['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt']-curr_dict['participants'][i+5]['stats']['magicDamageDealt'], 
						participant['stats']['physicalDamageDealt']-curr_dict['participants'][i+5]['stats']['physicalDamageDealt'],
						participant['stats']['totalDamageDealtToChampions']-curr_dict['participants'][i+5]['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions']-curr_dict['participants'][i+5]['stats']['magicDamageDealtToChampions'],
						participant['stats']['physicalDamageDealtToChampions']-curr_dict['participants'][i+5]['stats']['physicalDamageDealtToChampions'],
						participant['stats']['totalHeal']-curr_dict['participants'][i+5]['stats']['totalHeal'], 
						participant['stats']['totalUnitsHealed']-curr_dict['participants'][i+5]['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken']-curr_dict['participants'][i+5]['stats']['totalDamageTaken'], 
						participant['stats']['magicalDamageTaken']-curr_dict['participants'][i+5]['stats']['magicalDamageTaken'],
						participant['stats']['physicalDamageTaken']-curr_dict['participants'][i+5]['stats']['physicalDamageTaken'], 
						participant['stats']['goldEarned']-curr_dict['participants'][i+5]['stats']['goldEarned'], 
						participant['stats']['goldSpent']-curr_dict['participants'][i+5]['stats']['goldSpent'], 
						participant['stats']['totalMinionsKilled']-curr_dict['participants'][i+5]['stats']['totalMinionsKilled'], 
						participant['stats']['neutralMinionsKilled']-curr_dict['participants'][i+5]['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle']-curr_dict['participants'][i+5]['stats']['neutralMinionsKilledTeamJungle'], 
						participant['stats']['neutralMinionsKilledEnemyJungle']-curr_dict['participants'][i+5]['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt']-curr_dict['participants'][i+5]['stats']['totalTimeCrowdControlDealt'],
						participant['stats']['champLevel']-curr_dict['participants'][i+5]['stats']['champLevel'], 
						participant['stats']['visionWardsBoughtInGame']-curr_dict['participants'][i+5]['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame']-curr_dict['participants'][i+5]['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced']-curr_dict['participants'][i+5]['stats']['wardsPlaced'], 
						participant['stats']['wardsKilled']-curr_dict['participants'][i+5]['stats']['wardsKilled'], 
						participant['timeline']['creepsPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['creepsPerMinDeltas']['10-20'], 
						None, 
						participant['timeline']['creepsPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['creepsPerMinDeltas']['0-10'], 
						None, 
						participant['timeline']['xpPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['xpPerMinDeltas']['10-20'], 
						None, 
						participant['timeline']['xpPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['xpPerMinDeltas']['0-10'], 
						None, 
						participant['timeline']['goldPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['goldPerMinDeltas']['10-20'], 
						None, 
						participant['timeline']['goldPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['goldPerMinDeltas']['0-10'],
						None, 
						participant['timeline']['damageTakenPerMinDeltas']['10-20']-curr_dict['participants'][i+5]['timeline']['damageTakenPerMinDeltas']['10-20'], 
						None, 
						participant['timeline']['damageTakenPerMinDeltas']['0-10']-curr_dict['participants'][i+5]['timeline']['damageTakenPerMinDeltas']['0-10'],
						None)
					)
				else:	
					cursor.execute(Quer,
						(curr_dict['gameId'], curr_dict['participantIdentities'][i]['player']['summonerName'][3:].lower().replace(" ", ""), 
						curr_dict['participantIdentities'][7]['player']['summonerName'][0:3],roles[i-5],
						curr_dict['participantIdentities'][i-5]['player']['summonerName'][3:].lower().replace(" ", ""),
						participant['championId'], curr_dict['gameVersion'], "blue", participant['stats']['firstBloodKill'], participant['stats']['firstTowerKill'], participant['stats']['win'], curr_dict['gameDuration']/60,
						participant['stats']['turretKills'], participant['stats']['inhibitorKills'], participant['stats']['kills'],
						participant['stats']['deaths'], participant['stats']['assists'], participant['stats']['largestKillingSpree'], 
						participant['stats']['largestMultiKill'], participant['stats']['killingSprees'], participant['stats']['longestTimeSpentLiving'], 
						participant['stats']['doubleKills'], participant['stats']['tripleKills'], participant['stats']['quadraKills'], 
						participant['stats']['pentaKills'],  participant['stats']['unrealKills'], participant['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt'], participant['stats']['physicalDamageDealt'], participant['stats']['trueDamageDealt'], 
						participant['stats']['largestCriticalStrike'], participant['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions'], participant['stats']['physicalDamageDealtToChampions'], 
						participant['stats']['trueDamageDealtToChampions'], participant['stats']['totalHeal'], participant['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken'], participant['stats']['magicalDamageTaken'], participant['stats']['physicalDamageTaken'], 
						participant['stats']['trueDamageTaken'], participant['stats']['goldEarned'], participant['stats']['goldSpent'], 
						participant['stats']['turretKills'], participant['stats']['totalMinionsKilled'], participant['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle'], participant['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt'], participant['stats']['champLevel'], participant['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced'], participant['stats']['wardsKilled'], participant['stats']['firstBloodKill'], 
						participant['stats']['firstBloodAssist'], participant['stats']['firstTowerKill'], participant['stats']['firstTowerAssist'], 
						participant['stats']['firstInhibitorKill'], participant['stats']['firstInhibitorAssist'], 
						participant['timeline']['creepsPerMinDeltas']['10-20'], None, 
						participant['timeline']['creepsPerMinDeltas']['0-10'], None, 
						participant['timeline']['xpPerMinDeltas']['10-20'], None, 
						participant['timeline']['xpPerMinDeltas']['0-10'], None, 
						participant['timeline']['goldPerMinDeltas']['10-20'], None, 
						participant['timeline']['goldPerMinDeltas']['0-10'], None, 
						participant['timeline']['damageTakenPerMinDeltas']['10-20'], None, 
						participant['timeline']['damageTakenPerMinDeltas']['0-10'], None, 
						participant['stats']['totalDamageDealt']-curr_dict['participants'][i-5]['stats']['totalDamageDealt'], 
						participant['stats']['magicDamageDealt']-curr_dict['participants'][i-5]['stats']['magicDamageDealt'], 
						participant['stats']['physicalDamageDealt']-curr_dict['participants'][i-5]['stats']['physicalDamageDealt'],
						participant['stats']['totalDamageDealtToChampions']-curr_dict['participants'][i-5]['stats']['totalDamageDealtToChampions'],
						participant['stats']['magicDamageDealtToChampions']-curr_dict['participants'][i-5]['stats']['magicDamageDealtToChampions'],
						participant['stats']['physicalDamageDealtToChampions']-curr_dict['participants'][i-5]['stats']['physicalDamageDealtToChampions'],
						participant['stats']['totalHeal']-curr_dict['participants'][i-5]['stats']['totalHeal'], 
						participant['stats']['totalUnitsHealed']-curr_dict['participants'][i-5]['stats']['totalUnitsHealed'], 
						participant['stats']['totalDamageTaken']-curr_dict['participants'][i-5]['stats']['totalDamageTaken'], 
						participant['stats']['magicalDamageTaken']-curr_dict['participants'][i-5]['stats']['magicalDamageTaken'],
						participant['stats']['physicalDamageTaken']-curr_dict['participants'][i-5]['stats']['physicalDamageTaken'], 
						participant['stats']['goldEarned']-curr_dict['participants'][i-5]['stats']['goldEarned'], 
						participant['stats']['goldSpent']-curr_dict['participants'][i-5]['stats']['goldSpent'], 
						participant['stats']['totalMinionsKilled']-curr_dict['participants'][i-5]['stats']['totalMinionsKilled'], 
						participant['stats']['neutralMinionsKilled']-curr_dict['participants'][i-5]['stats']['neutralMinionsKilled'], 
						participant['stats']['neutralMinionsKilledTeamJungle']-curr_dict['participants'][i-5]['stats']['neutralMinionsKilledTeamJungle'], 
						participant['stats']['neutralMinionsKilledEnemyJungle']-curr_dict['participants'][i-5]['stats']['neutralMinionsKilledEnemyJungle'], 
						participant['stats']['totalTimeCrowdControlDealt']-curr_dict['participants'][i-5]['stats']['totalTimeCrowdControlDealt'],
						participant['stats']['champLevel']-curr_dict['participants'][i-5]['stats']['champLevel'], 
						participant['stats']['visionWardsBoughtInGame']-curr_dict['participants'][i-5]['stats']['visionWardsBoughtInGame'], 
						participant['stats']['sightWardsBoughtInGame']-curr_dict['participants'][i-5]['stats']['sightWardsBoughtInGame'], 
						participant['stats']['wardsPlaced']-curr_dict['participants'][i-5]['stats']['wardsPlaced'], 
						participant['stats']['wardsKilled']-curr_dict['participants'][i-5]['stats']['wardsKilled'], 
						participant['timeline']['creepsPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['creepsPerMinDeltas']['10-20'], 
						None, 
						participant['timeline']['creepsPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['creepsPerMinDeltas']['0-10'], 
						None, 
						participant['timeline']['xpPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['xpPerMinDeltas']['10-20'], 
						None, 
						participant['timeline']['xpPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['xpPerMinDeltas']['0-10'], 
						None, 
						participant['timeline']['goldPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['goldPerMinDeltas']['10-20'], 
						None, 
						participant['timeline']['goldPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['goldPerMinDeltas']['0-10'],
						None, 
						participant['timeline']['damageTakenPerMinDeltas']['10-20']-curr_dict['participants'][i-5]['timeline']['damageTakenPerMinDeltas']['10-20'], 
						None, 
						participant['timeline']['damageTakenPerMinDeltas']['0-10']-curr_dict['participants'][i-5]['timeline']['damageTakenPerMinDeltas']['0-10'],
						None)
					)
db.commit()
db.close()